version: '3.1'

services:
  backend:
    image: app-backend
    build:
      context: ./backend
    environment:
      - PORT=8000
    ports:
      - 8000:8000

  frontend:
    image: app-frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
